#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Pod-Constants
Version  : 0.19
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MG/MGV/Pod-Constants-0.19.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MG/MGV/Pod-Constants-0.19.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libpod-constants-perl/libpod-constants-perl_0.19-1.debian.tar.xz
Summary  : 'Include constants from POD'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Pod-Constants-license
Requires: perl-Pod-Constants-man

%description
Pod::Constants version 0.19
===========================
Pod::Constants allows you to extract data from your POD at run-time,
meaning you can do things like declare constants in POD and not have
to update two places at once every time you make a change.

%package license
Summary: license components for the perl-Pod-Constants package.
Group: Default

%description license
license components for the perl-Pod-Constants package.


%package man
Summary: man components for the perl-Pod-Constants package.
Group: Default

%description man
man components for the perl-Pod-Constants package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Pod-Constants-0.19
mkdir -p %{_topdir}/BUILD/Pod-Constants-0.19/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Pod-Constants-0.19/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Pod-Constants
cp LICENSE %{buildroot}/usr/share/doc/perl-Pod-Constants/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Pod/Constants.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Pod-Constants/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Pod::Constants.3
